USE project_comp_shop;

SHOW TABLES;

DROP TABLE IF EXISTS catalogs;

CREATE TABLE catalogs (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(120) NOT NULL
) COMMENT = 'Каталог товара';

DROP TABLE IF EXISTS producer;

CREATE TABLE producer (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(120) NOT NULL,
country VARCHAR(120) NOT NULL
) COMMENT = 'Производитель товара';

DROP TABLE IF EXISTS products;

CREATE TABLE products (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(120) NOT NULL,
description TEXT,
price DECIMAL(10, 2) UNSIGNED,
catalog_id INT UNSIGNED NOT NULL,
producer_id INT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT = 'Товар каталога';

DROP TABLE IF EXISTS order_line;

CREATE TABLE order_line (
order_id INT UNSIGNED NOT NULL,
product_id INT UNSIGNED NOT NULL,
amount TINYINT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT = 'Строка заказа';

DROP TABLE IF EXISTS `order`;

CREATE TABLE `order` (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
client_id INT UNSIGNED NOT NULL,
seller_id INT UNSIGNED NOT NULL,
total_price INT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT = 'Заказ';

DROP TABLE IF EXISTS client;

CREATE TABLE client (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
adress_id INT NOT NULL,
phone VARCHAR(50) NOT NULL,
email VARCHAR(100) DEFAULT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT = 'Информация о покупателе';

DROP TABLE IF EXISTS seller;

CREATE TABLE seller (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
post_id INT UNSIGNED NOT NULL
) COMMENT = 'Сотрудник магазина';

DROP TABLE IF EXISTS post;

CREATE TABLE post (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL
) COMMENT = 'Должности в магазине';

DROP TABLE IF EXISTS adress;

CREATE TABLE adress (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
city_id INT UNSIGNED NOT NULL,
street_id INT UNSIGNED NOT NULL,
house SMALLINT UNSIGNED NOT NULL,
flat SMALLINT UNSIGNED NOT NULL
) COMMENT = 'Адресс клиента';

DROP TABLE IF EXISTS street;

CREATE TABLE street (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL
) COMMENT = 'Улицы';

DROP TABLE IF EXISTS city;

CREATE TABLE city (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(120) NOT NULL
) COMMENT = 'Города проживания пользователей';

DROP TABLE IF EXISTS discounts;

CREATE TABLE discounts (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
client_id INT UNSIGNED NOT NULL,
product_id INT UNSIGNED NOT NULL,
discount TINYINT UNSIGNED DEFAULT NULL,
started_at DATETIME DEFAULT NULL,
finished_at DATETIME DEFAULT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT = 'Скидки для покупателей';

DROP TABLE IF EXISTS storehouse_products;

CREATE TABLE storehouse_products (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
product_id INT UNSIGNED NOT NULL,
amount TINYINT UNSIGNED,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT = 'Товар на складе';

DROP TABLE IF EXISTS order_step;

CREATE TABLE order_step (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
order_id INT UNSIGNED NOT NULL,
step_id INT UNSIGNED NOT NULL,
date_step_reg DATETIME,
date_step_end DATETIME DEFAULT NULL
) COMMENT = 'Статус заказа';

DROP TABLE IF EXISTS step;

CREATE TABLE step (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name_step VARCHAR(120) NOT NULL
) COMMENT = 'Состояния заказа';


# создание внешних ключей
USE project_comp_shop;

ALTER TABLE products
	ADD CONSTRAINT products_catalog_id_fk
		FOREIGN KEY (catalog_id) REFERENCES catalogs(id) 
			ON DELETE RESTRICT,
	ADD CONSTRAINT products_producer_id_fk
		FOREIGN KEY (producer_id) REFERENCES producer(id)
			ON DELETE RESTRICT;

ALTER TABLE order_line 
	ADD CONSTRAINT order_line_product_id_fk
		FOREIGN KEY (product_id) REFERENCES products(id)
			ON DELETE CASCADE;
ALTER TABLE order_line 
	ADD CONSTRAINT order_line_order_id_fk
		FOREIGN KEY (order_id) REFERENCES `order`(id)
			ON DELETE CASCADE;
			
ALTER TABLE storehouse_products
	ADD CONSTRAINT storehouse_products_product_id_fk
		FOREIGN KEY (product_id) REFERENCES products(id)
			ON DELETE CASCADE;

ALTER TABLE discounts
	ADD CONSTRAINT discounts_product_id_fk
		FOREIGN KEY (product_id) REFERENCES products(id)
			ON DELETE NO ACTION,
	ADD CONSTRAINT discounts_client_id_fk
		FOREIGN KEY (client_id) REFERENCES client(id)
			ON DELETE NO ACTION;
			
ALTER TABLE `order` 
	ADD CONSTRAINT order_client_id_fk
		FOREIGN KEY (client_id) REFERENCES client(id)
			ON DELETE NO ACTION,
	ADD CONSTRAINT order_seller_id_fk
		FOREIGN KEY (seller_id) REFERENCES seller(id)
			ON DELETE NO ACTION;

ALTER TABLE order_step
	ADD CONSTRAINT order_step_order_id_fk
		FOREIGN KEY (order_id) REFERENCES `order`(id)
			ON DELETE CASCADE,
	ADD CONSTRAINT order_step_step_id_fk
		FOREIGN KEY (step_id) REFERENCES step(id)
			ON DELETE NO ACTION;

ALTER TABLE client
MODIFY COLUMN adress_id INT UNSIGNED NOT NULL;
ALTER TABLE client
	ADD CONSTRAINT client_adress_id_fk
		FOREIGN KEY (adress_id) REFERENCES adress(id)
			ON DELETE NO ACTION;

ALTER TABLE adress
	ADD CONSTRAINT adress_city_id_fk
		FOREIGN KEY (city_id) REFERENCES city(id)
			ON DELETE NO ACTION,
	ADD CONSTRAINT adress_street_id_fk
		FOREIGN KEY (street_id) REFERENCES street(id)
			ON DELETE NO ACTION;

ALTER TABLE seller
	ADD CONSTRAINT seller_post_id_fk
		FOREIGN KEY (post_id) REFERENCES post(id)
			ON DELETE RESTRICT;
		
		